### ISSUE TITLE
CLA for go-mtpfs contribution

### ISSUE THREAD

**Issue by hanwen** [gnanderson/bin#1]
I have been trying to reach you at graham@andtech.eu, but that email is bouncing. 

'm writing you over a contribution (see below) you made to an
open-source package I wrote, go-mtpfs. It has been brought to my
attention that I should have asked for a CLA (Contributor License
Agreement) before accepting your change.

Would you fill out a CLA for this contribution? The alternative is
that I will have to remove the change from the source code. You can
fill out the CLA at

  https://cla.developers.google.com/clas

it takes just a minute, and I myself will have no access to the
personal data you enter.

thanks!

Han-Wen

(background: I work for Google, which means the copyrights for the
software belongs to Google too. Google has a policy for requiring CLAs
for external contributions to such projects, even if they are not
official projects)

commit 061b88c285486686353c310de687cdaa1d76f64d
Author: Graham Anderson <graham@andtech.eu>
Date:   Mon Jul 1 01:39:41 2013 +0100

    fs/android: update call to go-fuse read result API

**Comment by hanwen** [comment]
CLA found from graham.anderson@gmail.com .

**Comment by gnanderson** [comment]
Thanks for your patience, and thanks for this useful code... Makes my life
very much easier.
